### ISSUE TITLE
Broadcast input array error

### ISSUE THREAD

**Issue by T3chN1nja** [HDCharles/TTS-to-PnP-Cards#2]
I exported my TTS cards into three different files. When I try to use the application I keep getting the below error. Any ideas why?

![image](https://user-images.githubusercontent.com/88980753/129485592-55fc88e6-67a8-4ff1-ae87-83fb6e90a964.png)

**Comment by T3chN1nja** [comment]
Tried exporting my TTS files as JPEG instead of PNG and I no longer received that error. Does the program not support PNG?

**Comment by HDCharles** [comment]
ya I didn't realize png use a 4 format input when I made this, The new version should be working.
